name: mlt_menu
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  form_inputs:
    path: packages/form_inputs
  table_repository:
    path: packages/table_repository
  print_repository:
    path: packages/print_repository
  order_repository:
    path: packages/order_repository
  food_repository:
    path: packages/food_repository
  authentication_repository:
    path: packages/authentication_repository
  category_repository:
    path: packages/category_repository
  user_repository:
    path: packages/user_repository
  awesome_dialog: ^3.2.0
  equatable: ^2.0.5
  firebase_auth: ^4.16.0
  firebase_core: ^2.25.0
  flex_color_scheme: ^7.3.1
  flutter_spinkit: ^5.2.0
  go_router: ^13.1.0
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  firebase_messaging: ^14.7.11
  intl: ^0.19.0
  cloud_firestore: ^4.15.0
  fluttertoast: ^8.2.4
  logger: ^2.0.2+1
  convex_bottom_bar: ^3.2.0
  flutter_bloc: ^8.1.3
  formz: ^0.6.1
  flutter_animate: ^4.5.0
  tiengviet: ^1.0.0
  readmore: ^2.2.0
  flutter_slidable: ^3.0.1
  grouped_list: ^5.1.2
  dotted_border: ^2.1.0
  image_picker: ^1.0.7
  firebase_storage: ^11.6.6
  freezed_annotation: ^2.4.1
  flutter_svg: ^2.0.10+1
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  badges: ^3.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  
  assets:
    - assets/map_style.txt
    - assets/image/
    - assets/image/banner/
    - assets/image/plate_food/
    - assets/image/image_recipe/
    - assets/icon/
    - assets/.env
